### ISSUE TITLE
show timestamp for each message

### ISSUE THREAD

**Issue by flokli** [smooch/smooch-web#407]
Hey,

in a customer chat scenario, it might make sense to show a timestamp (or `x minutes ago`) below each message. Are there already plans to integrate something like this a a configure option into smooch-js?

**Comment by lemieux** [comment]
Hey @flokli, that's indeed a good idea. I'll bring it up to the team and come back to you when I have more details.

Thanks!

**Comment by flokli** [comment]
Hey @lemieux Awesome, thanks!

**Comment by lemieux** [comment]
Hey @flokli, seemed like this idea took a loooong way to make it up the priority chain, but it finally has!

The [latest release](https://github.com/smooch/smooch-web/releases/tag/4.3.0) has the new timestamp.

Very sorry for the long wait!

**Comment by flokli** [comment]
yay!
