### ISSUE TITLE
Cannot read property 'conversationStarted' of undefined | smooch.jsx:297 

### ISSUE THREAD

**Issue by guivazcabral** [smooch/smooch-web#536]
Hi. I'm getting this error when I programatically open the conversation widget and send a message with
`Smooch.open();` and `Smooch.sendMessage({text: 'message'});`
Although, if I open the conversation widget manually (by clicking on the smooch circle) and only then do the `Smooch.open();` and `Smooch.sendMessage({text: 'message'});` the error no longer occurs.

Any clue why this happens?

**Comment by lemieux** [comment]
Hi,

my first guess would be about timing. How are you initializing the widget before calling `Smooch.open()` (and when..?). I'm guessing it didn't have time to init properly before both methods are called.

**Comment by lemieux** [comment]
I'll close this one since it shouldn't happen with the newest version. Feel free to reopen if it still happen.
