### ISSUE TITLE
Possibility of sending message without posting a request to backend server

### ISSUE THREAD

**Issue by Carson12345** [smooch/smooch-web#617]
I am aware that Smooch provides the button postback function. I am in need of a function to do a modified version of it as following: I want to send a message of the button text right after clicking the button, lets say the bot(App Maker) provide three button wrapped in a message, namely "US", "UK" and "China", then the App user click "US", not only a postback is made, but the chosen option's button text is also sent as a message, somehow like the cardAction.imback of Microsoft Bot Framework Web SDK.

May I know if it is possible please? I have tried to modified the code myself by it only works in certain browsers, I really hope to seek the advice from Smooch on some suggested approaches. Thank you!

**Comment by mspensieri** [comment]
I think you might be looking for [Reply Actions](https://docs.smooch.io/rest/#reply)

**Comment by Carson12345** [comment]
@mspensieri Hi thanks so much for leaving the advice! reply actions is good, but can they send action id? I am in need of something that can send action ids too..

**Comment by mspensieri** [comment]
It doesn't pass the `_id` of the message action, but you can specify any `payload` string you want for the action (similar to a postback), and it will be delivered with the message as `message.payload`. You can use that value to either take action on your bot, or find the action in the smooch conversation history

**Comment by Carson12345** [comment]
So much thanks for your advice! I will keep exploring it!
