### ISSUE TITLE
wont load with vuejs 

### ISSUE THREAD

**Issue by jaubut** [smooch/smooch-web#628]
Anyone had an exemple with vuejs ?

**Comment by lemieux** [comment]
@jaubut did you try the latest version (v4.0.0)? I should render fine using Vuejs. Not sure exactly how the lifecycle works in Vue, but in React, you can call `Smooch.init()` in `componentDidMount()` of a component and it should work fine.

**Comment by jaubut** [comment]
doesnt work.. Im still looking around to see what im doing wrong

**Comment by jaubut** [comment]
It seems like its the init method that bugs..

**Comment by jaubut** [comment]
/Users/jeremieaubut/jaubut_space/node_modules/smooch/lib/index.js:1052
    if(!window.matchMedia) {
        ^

ReferenceError: window is not defined

**Comment by lemieux** [comment]
I'm guessing you are doing server-side rendering, otherwise I don't see a case where `window` wouldn't be defined. Our Web Messenger doesn't support server-side rendering as some of its dependencies are not working in a non-browser environment.

**Comment by jaubut** [comment]
Haaaa good to know thanks :)

**Comment by lemieux** [comment]
No problem :)

**Comment by jaubut** [comment]
Error in beforeMount hook: "TypeError: Smooch.init is not a function"

**Comment by jaubut** [comment]
Error in beforeMount hook: "TypeError: Smooch.init is not a function"
