### ISSUE TITLE
Replacement for whispers

### ISSUE THREAD

**Issue by faelsoto** [smooch/smooch-web#643]
I've been trying to contact you guys for 20 minutes via chat and I haven't received a reply. It's impossible to find a support email, so I'm opening an issue.

I'm very disappointed of smooch, to say the least. Last month you removed completely the whispers and I didn't receive not even one email regarding this breaking change. I'm using smooch as a sales channel, and now I've lost a full month of users not receiving messages. And it could have been way more than a month, since I just logged in to add a new whisper only to not find that section, then Google it and figure out it has been removed.

What a mess. The worst thing is that the «replacement» is to trigger an API call or something like that. I can't afford so many hours just to make a feature work as it was intended. I just want to greet the user when he loads the page, that's it. I tried referring to this documentation, but there's just a way to send a message on the user's behalf, but not on the agent side.

I'm about to cancel my Smooch services if this is not promptly fixed.

Thanks.

**Comment by gozman** [comment]
Hi Rafael,

As we have recently communicated, in the past year we have built relationships with thousands of great businesses, and we have found that software makers are at the forefront of innovation with Smooch. It is for these reasons that we have doubled down our investments in platform resilience, availability, security and assurance and that we announced updates to our Packages and Pricing Plans tailored to meet the needs of our maker community.  

As part of these updates, we also sunset our Whispers feature as of October 1st, 2017. Whispers do not align with Smooch’s focus on enabling software makers to add messaging to their products. To refocus our efforts, we have made the decision to no longer support the feature. 

We reached out to all of our users and customers about this on July 4th and again 3 months later in October when we disabled the functionality across our base. I looked into your account and noticed that you had unsubscribed from our e-mails and thus did not receive these features. Without you opting-in to the e-mails or providing consent through becoming a paying customer, we were unfortunately not able to include you in this communication.

We recognize this change will have an impact on your business. In an effort to minimize the impact, we have provided two options which we hope will help in your transition away from Whispers:

1) We’ve put together a guide which helps you build Whispers-like functionality directly into your own software.  If this is helpful to you, you can find the documentation [here](https://docs.smooch.io/guide/whisper-replacements/).

2) Alternatively, we would advise you to consider Intercom as an alternative solution provider as their products may solve the use cases you currently solve with Whispers (although the channel options are more limited). Intercom allows you to see and track the people using your web and mobile apps, and helps you communicate with them for marketing, sales, and support in a way that’s contextual and personal. If this is interesting to you, Intercom has agreed to offer Smooch Whispers users a 50% discount for their first 3 months. [Visit their site to learn more](https://www.intercom.com/drlp/sponsor/ngrmga?utm_source=smooch-email).

Note that all communications besides Whispers messages will continue to work normally after October 1st. That includes messages sent via the Smooch API and all our integrations.

**Comment by faelsoto** [comment]
I've opted out because I don't want to receive promotional emails from the services I use; not for site-breaking changes. You should have a separate email list, since these are priority.

I'm cancelling my account.
