### ISSUE TITLE
Mobile: Page scrolls back to top on opening (unwanted)

### ISSUE THREAD

**Issue by stevepiron** [smooch/smooch-web#645]
Hello,

As scroll gets locked on `html` when opening Smooch (by using a combination of `overflow: hidden; height: 100%; max-height: 100%;` scroll position gets reset to zero, which we can see when opening the conversation (page jumps back to top during the opening animation).

Ideally, scroll position should be saved right before opening and set back as soon as the viewport gets locked.

I've seen it's been taken care of on close already: https://github.com/smooch/smooch-web/pull/246

**Comment by nathang21** [comment]
+1 We just upgraded our site to widget 4.x and now Everytime we close the chat on mobile it scrolls to the top of the page.

**Comment by kant312** [comment]
+1

**Comment by LouVerdun** [comment]
+1

**Comment by maximepalau** [comment]
+1

**Comment by pablofernandezgh** [comment]
+1
