### ISSUE TITLE
Are custom builds no longer supported?

### ISSUE THREAD

**Issue by nikkwong** [smooch/smooch-web#648]
Hi, the documentation at smooch.io mentions custom builds, and I can see custom building available up until recently in the release history. 

Has smooch dropped support for this? I would really like to use it if it's still compatible with the smooch API, even if it's not officially supported.

Thanks.

**Comment by spasiu** [comment]
Hi @nikkwong. We recently limited support for custom builds to certain paid tiers. If you're interested, please consider applying for our Early Stage plan for startups https://smooch.formstack.com/forms/early_stage.
