### ISSUE TITLE
4.5.0 tarball in npm registry is empty

### ISSUE THREAD

**Issue by suicide** [smooch/smooch-web#649]
Hi,

the package of release 4.5.0 in the public npm registry (https://registry.npmjs.org/smooch/-/smooch-4.5.0.tgz) is more or less empty. there is only a package.json, README.md and the LICENSE file, but not the code.

Can you fix that?

Cheers
Patrick

**Comment by lemieux** [comment]
Hey, we're pushing a fix for it as we speak. Very sorry about that, a misconfiguration made its way in the last release.

**Comment by lemieux** [comment]
Release 4.5.1 should have the fix for this.
