### ISSUE TITLE
Feature Request: Adding support for Google tag manager

### ISSUE THREAD

**Issue by grantkemp** [smooch/smooch-web#651]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

 **I'm submitting a ...**
  - [ ] bug report
  - [ x] support request => Please do not submit support request here, see note at the top of this template.

Currently the site doesn't have documentation for how to support tag manager.  This is a problem that prevents us currently using the system  as we are unable to attribute contacts which come through smooch.

Otherw solutions have specific plugins that support tag manager out of the box without needing custom development.  

Is this the case for smooch? If so please can you link directly to the documentation.  

Events we need: 
1. Initial Message sent. ( this should not be fired for subsequent messages sent for that session
2. Validated Lead - if the lead is not spam lead - there should be an even that the team can send to mark it as a validated lead.

**Comment by mspensieri** [comment]
As mentioned in the issue template, GitHub issues are reserved for bug reports only. Please visit our [help page](https://smooch.io/help/) to view your support options if you would like to submit a feature request.

That being said, we have documentation on how to add Smooch using Google Tag Manager in our documentation [here](https://docs.smooch.io/faq/web-messenger/#google-tag-manager)

**Comment by grantkemp** [comment]
@mspensieri  The link you sent only shows how to inject the code for your library in via Google Tag manager. This doesn't cover the tracking and injecting it into Google Analytics via Google Tag Manager ( which currently doesn't appear to be supported out of the box)  I have raised feature request previously but never got a response hence me seeking clarity on Github. 

( Incidentally the advice you give on injecting your code in via Google Tag Manager is actually not good practice and could impact your customers site - suggest that you revisit that as well!) 

Hope this helps 

Cheers
