### ISSUE TITLE
Compress Static smooch asset Images

### ISSUE THREAD

**Issue by nathang21** [smooch/smooch-web#657]
What is the current behavior?
Smooch used un-minified static images for integration thumbnails, etc. 

Please provide the steps to reproduce and, if possible, a minimal demo of the problem via
https://plnkr.co, https://codepen.io/, or similar (e.g. a GitHub repository).
Run a website with Smooch web-messenger installed through Any Page speed analyzer, etc.
GTmetrix
https://gtmetrix.com/
https://www.webpagetest.org/

What is the expected behavior?
These assets which are constantly requested, could be further optimized and have a big impact on page load speed. Expanding cache headers would help a lot on subsequent requests (as requested on #535), but the initial request is still a bit painful.

Please tell us about your environment:

Delivery method: CDN
Version: 4.6.1
Browser: ALL
OS: ALL

Examples of major savings:
`Losslessly compressing https://cdn.smooch.io/bca0d1056c4ee94c28fdc9b05f79e1d8.png could save 1.6KiB (52% reduction). 

Losslessly compressing https://cdn.smooch.io/b1d879a94d135c4586d499f377bc7418.png could save 1.5KiB (52% reduction). 

Losslessly compressing https://cdn.smooch.io/3a9b9d0f58b2c72b377140b1785431f3.png could save 1.4KiB (44% reduction).

Losslessly compressing https://cdn.smooch.io/83c94bf974d59ac0ed59f8a69b48bdcf.png could save 1.2KiB (40% reduction). 

Losslessly compressing https://cdn.smooch.io/9d69b94a58a6503b6d6723476ebba41e.png could save 1.0KiB (65% reduction). 

Losslessly compressing https://cdn.smooch.io/2b5e86da0f91443e8a83f7883ca9d10f.png could save 1.0KiB (62% reduction). 

Losslessly compressing https://cdn.smooch.io/d7e8b61376385a28b28e39f1d540763c.png could save 1011B (53% reduction). 

Losslessly compressing https://cdn.smooch.io/81567450d8214329730cd429cb4083ff.png could save 929B (38% reduction).

Losslessly compressing https://cdn.smooch.io/2bc532f57a2074a56fc036334188e40a.png could save 806B (48% reduction).

Losslessly compressing https://cdn.smooch.io/8ddaae5507ef13e91e228c0494fd0ae1.png could save 765B (51% reduction).

Losslessly compressing https://cdn.smooch.io/e0fcb9f29bbe719fa21691fe1262984c.png could save 682B (33% reduction). 

Losslessly compressing https://cdn.smooch.io/787ea80778a3c39701aa69acbcb53035.png could save 550B (21% reduction).`

**Comment by mspensieri** [comment]
Thanks for the report, I've filed an issue internally to review our assets and optimize where possible.

w.r.t. the caching issue 

> Expanding cache headers would help a lot on subsequent requests (as requested on #535)

I'm not sure I understand the problem. These assets should have a cache lifetime of 7,300 days

```
$ curl -I https://cdn.smooch.io/bca0d1056c4ee94c28fdc9b05f79e1d8.png

cache-control: max-age=630720000, public
```

Can you elaborate?

**Comment by nathang21** [comment]
Thanks for the response, think there could be some big savings here with compression.

I'll file a new issue for the caching, as not to confuse this topic. Plus since the other one is closed (I saw your comment as well).

**Comment by b0uh** [comment]
Hi @nathang21 , the assets has been compressed in the latest release of the SDK [4.12.3](https://github.com/smooch/smooch-web/releases/tag/4.12.3), so I'm closing this issue.
