### ISSUE TITLE
Carousel support on IE11

### ISSUE THREAD

**Issue by rjam** [smooch/smooch-web#659]
**I'm submitting a ...**
  - [x] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

**What is the current behavior?**
On IE11, carousels overlap the sender's thumb and scroll/arrows don't work. 

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem** via
https://plnkr.co, https://codepen.io/, or similar (e.g. a GitHub repository).
Boot up a chat that sends a carousel with more than 2 or 3 items to test the scroll.

 **What is the expected behavior?**
Like on other browsers, the carousel and arrows should show up correctly and the arrows/horizontal scrolling should be functional. 

 **Please tell us about your environment:**
- Delivery method: CDN
- Version: 4.8.2
- Browser: IE11
- OS: Windows (10)

**Comment by dannytranlx** [comment]
Hi @rjam, thanks for the detailed bug report. We will take a look at this bug, it's been filed internally.

**Comment by spasiu** [comment]
This issue was fixed in [Release v4.12.10](https://github.com/smooch/smooch-web/releases/tag/4.12.10).
