### ISSUE TITLE
Custom button in v4.8.2

### ISSUE THREAD

**Issue by lucasreppewelander** [smooch/smooch-web#660]
Version: `CDN 4.8.2`

Hi, I just upgrade from 3.15 to 4.8.2.

In 3.15 we could hide the default button to bind the `Smooch.open()` to my own customized button, isn't this possible anymore in 4.8.2?

I've also tried the `embedded: true` option but that doesn't seem to run `init()` command.
in the new iframe version it seems I cant hide the button with CSS and also being able to show the standard messaging pane.

I would really like to use my own button, is this possible?

**Comment by mspensieri** [comment]
You can customize the button icon and size at init time, by uploading a new icon on the Smooch dashboard, or by using the update integration API. More information [here](https://docs.smooch.io/guide/web-messenger/#display-style).

Is this what you're looking for?

**Comment by lucasreppewelander** [comment]
Spec says square button. hehe

but I managed to solve it by hooking in to the events `widget:opened` and `widget:closed` and adds/removes a css class on the iframe, and the offset it using css, it works pretty neat.

Thank you for an awesome tool!

**Comment by mspensieri** [comment]
I think you can bypass the square icon restriction by customizing the button size to match your image. You can also supply a PNG with transparency to not have a literal square
