### ISSUE TITLE
message:received called on page load

### ISSUE THREAD

**Issue by coreyworrell** [smooch/smooch-web#662]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

 **I'm submitting a ...**
  - [x] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

 **What is the current behavior?**
Hello,

We are following guide here https://github.com/smooch/custom-smooch-web-ui for using a custom UI for Smooch. We are having an issue though with two items:

Setting a message as read/clearing the unread count. This does not seem to be possible without using the full REST API? It seems to be the only functionality that is missing from this method. And it seems silly to load in another full JavaScript library just to use one method.. So currently with this method you recommend (per Github link above), if a user sees the messages, and then leaves site, when they come back later it will always say there are new messages, until the user replies again.

Second, when there are unread messages, for some reason on page load the `message:received` event is called for each unread message. And it is called before the `Smooch.init().then()` function runs... So again, using the method recommended of:

```
var conversation = Smooch.getConversation();
conversation.messages.forEach(displayMessage);
```

Unread messages will be appended to that list first, and then the entire conversation afterwards, so duplicate messages will be present. Even if the unread count could be reset to 0, this would still cause issues if a user had the chat window hidden, and then left site and returned (or refreshed page, etc).

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem** via
https://plnkr.co, https://codepen.io/, or similar (e.g. a GitHub repository).
https://github.com/smooch/custom-smooch-web-ui

 **What is the expected behavior?**
`message:received` is not called on page load, but only when a new message first arrives. Method should exist to decrement or reset the unread message count.

 **Please tell us about your environment:**
- Delivery method: CDN
- Version (can be found using `Smooch.VERSION` in your browser): 4.9.0
- Browser: all
- OS: all

**Comment by alavers** [comment]
Thanks for the detailed report! I'll file a pair of issues internally to see what we can do for you here.

**Comment by alavers** [comment]
First, the `message:received` event that is firing for unread messages on page load was behavior related to a feature that no longer exists. I think it should probably stop doing that.

Second, exposing a `Smooch.resetUnreadCount` is very doable. Was a bit surprised it isn't there already.

**Comment by coreyworrell** [comment]
Awesome, thanks very much. Looking forward to those updates.

**Comment by b0uh** [comment]
@coreyworrell Sorry for the delay. The version 4.12.14 includes a fix that prevents `message:received` to be triggered during the initialization of the Web Messenger.

It should resolve your issue. Let me know if it is not the case.

**Comment by coreyworrell** [comment]
@b0uh no worries, thanks for the update!
