### ISSUE TITLE
Is there any way to fire/listen user typing event?

### ISSUE THREAD

**Issue by phamlehoaian** [smooch/smooch-web#670]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

 **I'm submitting a ...**
  - [ ] bug report
  - [x] support request => Please do not submit support request here, see note at the top of this template.

 **What is the current behavior?**
I am developing a new custom UI chat box for my client. He want me show user typing event but I can not find document to listening conversation typing event. Please help me if there is any way to do this task. Thank you.

**Comment by mspensieri** [comment]
Currently there is no way to manage typing indicators programmatically, but I'll bring your suggestion to the team. Thanks!

**Comment by maxlacoste92** [comment]
This is now supported as of [v4.17.15](https://github.com/smooch/smooch-web/releases/tag/4.17.15).
