### ISSUE TITLE
Smooch script CDN not gzipped

### ISSUE THREAD

**Issue by danielcardoso5** [smooch/smooch-web#672]
The file being downloaded from the CDN by the smooch script is not gzipped. It amounts to more than 700kb of js.

![captura de ecra 2019-02-21 as 15 06 45](https://user-images.githubusercontent.com/1761147/53178864-8f0b1b80-35ea-11e9-8f01-c1afcd3667f6.png)

**Comment by mspensieri** [comment]
Hi @danielcardoso5, could this be related to your browser config? The file is gzipped for me

<img width="1054" alt="screen shot 2019-03-01 at 9 02 53 am" src="https://user-images.githubusercontent.com/2286852/53642958-eb7cc500-3c00-11e9-89a1-f19303691a6b.png">

**Comment by danielcardoso5** [comment]
Hi @mspensieri ,
I can confirm it's being gzipped, don't know what made this happen.
Thanks
