### ISSUE TITLE
prechatCapture does not display when embedded: true

### ISSUE THREAD

**Issue by dmasiero** [smooch/smooch-web#675]
This _maybe_ a bug. When `embedded: false`, `prechatCapture` works as expected. When `embedded: true`, prechatCapture does not work. [Here is code example](https://codepen.io/anon/pen/JQPbPa), simply insert a demo `appId`.

**Comment by TomFellows** [comment]
Thanks for the heads up, this is now supported as of [v4.19.4](https://github.com/smooch/smooch-web/releases/tag/4.19.4).
