### ISSUE TITLE
Some data automatically masked !!

### ISSUE THREAD

**Issue by SherifBashar** [smooch/smooch-web#676]
Hi,

I sent this message 4501-0136-5373-6750-3770-1005-3736-3900-1440-2401-0720-19

and the output was ************6750-3770-1005-3736-3900-1440-2401-0720-19

I would like to know how to disable this feature.

Thanks.

**Comment by mspensieri** [comment]
Looks like the first 16 characters of your message were classified as a credit card. You can disable this auto-masking by setting [`maskCreditCardNumbers`](https://docs.smooch.io/rest/#app-settings) to `false` via the [Update App API](https://docs.smooch.io/rest/#update-app)

**Comment by SherifBashar** [comment]
Got it .. thanks
