### ISSUE TITLE
js cdn doesn't work

### ISSUE THREAD

**Issue by JavaPixelArt** [smooch/smooch-web#680]
https://stackoverflow.com/questions/57885269/https-cdn-smooch-io-frame-4-23-0-min-js-is-pending

**Comment by wmora** [comment]
Hi, could you provide more info about this issue? Is this happening all the time? Is it happening from a specific browser?

**Comment by JavaPixelArt** [comment]
Good day, it was caused by another script before, not your issue, sorry

ср, 11 сент. 2019 г., 16:34 William Mora <notifications@github.com>:

**Comment by wmora** [comment]
Glad to know it works now, thanks for reporting back
