### ISSUE TITLE
Forms sometimes are not submitted when all fields are validated

### ISSUE THREAD

**Issue by ismaelga** [smooch/smooch-web#683]
**I'm submitting a ...**
  - [X] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

 **What is the current behavior?**

Sometimes the forms are not auto submitted after all fields are validated. We investigated and the issue seems be caused because props are being used to store the input values which is a bad practice as they can be cleared out if any other prop is updated (although I've not debugged to see which prop is causing the update on our case)

 **What is the expected behavior?**

The form to be always submitted when all fields are validated

 **Please tell us about your environment:**

We are running our fork from v1.22.9 but checked and newest version have no fix for this issue

 **Other information** 

I've also submitted a ticket on our fork which has a bit more information https://github.com/smooch-partners/lvmh-web/issues/1

**Comment by fxlemire** [comment]
Hi @ismaelga, thank you for the report, we will look into this issue and prioritize it.

**Comment by ismaelga** [comment]
Hi @fxlemire, any updates on this? Any idea when can we expect a fix for this?

**Comment by fxlemire** [comment]
[Web SDK 4.28.3](https://github.com/smooch/smooch-web/releases/tag/4.28.3) is now released, fixing this issue.
